import express from 'express';

const router = express.Router();

// Simple embedded chat/booking widget scaffold (iframe content)
router.get('/widget/embed', (req, res) => {
  const clientId = req.query.clientId || '';
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Johnblex AI Widget</title>
<style>
  body{margin:0;font-family:system-ui, -apple-system, BlinkMacSystemFont,Segoe UI, sans-serif;background:#0d1321;color:#fff;}
  .frame{padding:18px;display:flex;flex-direction:column;gap:12px;height:100vh;box-sizing:border-box;}
  .field{display:flex;flex-direction:column;gap:6px;}
  input,button{border-radius:12px;border:1px solid rgba(255,255,255,0.18);background:rgba(255,255,255,0.05);color:#fff;padding:0.7rem;}
  button{cursor:pointer;border:none;background:linear-gradient(135deg,#5e4bff,#55c2ff);font-weight:600;}
  button:disabled{opacity:0.55;cursor:not-allowed;}
  .status{font-size:0.9rem;color:rgba(255,255,255,0.7);}
</style>
</head>
<body>
  <div class="frame">
    <h2 style="margin:0;font-size:1.2rem">Book a demo</h2>
    <p style="margin:0;color:rgba(255,255,255,0.7)">Leave your details and we’ll reach out shortly.</p>
    <div class="field"><label>First name<input id="firstName" placeholder="First name" /></label></div>
    <div class="field"><label>Surname<input id="surname" placeholder="Surname" /></label></div>
    <div class="field"><label>Email<input id="email" placeholder="Email" type="email" /></label></div>
    <div class="field"><label>Phone<input id="phone" placeholder="Phone (optional)" /></label></div>
    <div class="field"><label>Company<input id="company" placeholder="Company (optional)" /></label></div>
    <button id="submit">Book demo</button>
    <p class="status" id="status">Your information stays private.</p>
  </div>
  <script>
    const statusEl = document.getElementById('status');
    const submit = document.getElementById('submit');

    // Token can be passed using the script query param (generated by admin API)
    const urlParams = new URLSearchParams(window.location.search);
    const widgetToken = urlParams.get('token') || '';

    async function postLead() {
      const firstName = document.getElementById('firstName').value.trim();
      const surname = document.getElementById('surname').value.trim();
      const email = document.getElementById('email').value.trim();
      const phone = document.getElementById('phone').value.trim();
      const company = document.getElementById('company').value.trim();

      if (!firstName || !surname || !email) {
        statusEl.textContent = 'First name, surname, and email are required.';
        return;
      }

      submit.disabled = true;
      statusEl.textContent = 'Sending...';

      try {
        const res = await fetch('${process.env.BACKEND_URL || 'http://localhost:4000'}/api/widget/lead', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: 'Bearer ' + widgetToken,
          },
          body: JSON.stringify({
            firstName,
            surname,
            email,
            phone,
            companyName: company,
            chatbotId: clientId,
          }),
        });

        const data = await res.json();
        if (!res.ok) throw new Error(data.error || 'Failed');
        statusEl.textContent = 'Thank you! Your demo has been booked. Our team will contact you shortly.';
        submit.disabled = true;
      } catch (err) {
        statusEl.textContent = err.message || 'Submission failed';
      } finally {
        submit.disabled = false;
      }
    }

    submit.addEventListener('click', postLead);
  </script>
</body>
</html>
  `;

  res.setHeader('Content-Type', 'text/html');
  res.send(html);
});

export default router;
